//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_Demo_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Student
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime DOB { get; set; }
        public string Gender { get; set; }
        public decimal Mobile_No { get; set; }
        public string City { get; set; }
    }
}
